# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/SignZeroExtend.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/ROM.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/RegFile.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/RAM.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/PC.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/Multiplexer5.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/Multiplexer32ForB.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/Multiplexer32For4.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/Multiplexer32For2.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/ControlUnit.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/ALU.v
  D:/Vivado_Data/CPU_single/CPU_single.srcs/sources_1/new/CPU_single.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_Data/CPU_single/CPU_single.cache/wt [current_project]
set_property parent.project_dir D:/Vivado_Data/CPU_single [current_project]
catch { write_hwdef -file CPU_single.hwdef }
synth_design -top CPU_single -part xc7a35tcpg236-1
write_checkpoint CPU_single.dcp
report_utilization -file CPU_single_utilization_synth.rpt -pb CPU_single_utilization_synth.pb
